excluded:
  - "**/*/NeedleGenerated.swift"
  - "Tuist"

force_cast: # From https://realm.github.io/SwiftLint/force_cast.html
  warning # 강제 캐스팅은 error에서 warning으로 변경

identifier_name:
  min_length:
    warning: 1

nesting:
  type_label:
    warning: 3

type_name:
  max_length:
    warning: 60
