title: "[Bug] : "
labels: ["Beta_test_bug_report"]

body:
  - type: markdown
    attributes:
      value: |
        ## 테스트 App 주의 사항!
        - 가사가 없는 것이 있을 수 있습니다.
        - 건의사항 페이지 버그 제보는 이용하시면 안됩니다 ( 기능은 사용할 수 있지만 트래픽 당 서버 요금이 청구되어 베타테스트 때는 사용하지 않을 겁니다)
        - 플레이어는 백그라운드 재생이 되지만 밖에서 재생을 멈출 수 없는 상태입니다.
  - type: input
    id: contact
    attributes:
      label: 연락처
      description: "디스코드 아이디를 입력해 주세요."
      placeholder: ex) 김대희#3478
    validations:
      required: true
  - type: input
    id: ios-version
    attributes:
      label: iOS 버전
      description: "사용하고 계신 기기의 iOS 버전을 입력해 주세요."
      placeholder: ex) 16.4(a)
    validations:
      required: true
  - type: input
    id: iphone-num
    attributes:
      label: iPhone 기종
      description: "사용하고 계신 iPhone 기종을 입력해 주세요."
      placeholder: ex) iPhone 14 Pro Max
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 로그인 플랫폼
      description: "로그인한 방식을 선택해 주세요."
      options:
        - 로그인 안함
        - Apple
        - Google
        - Naver
    validations:
      required: true
  - type: textarea
    attributes:
      label: 버그 상세설명
      description: |
        버그를 상세히 설명해 주세요!
      placeholder: |
        ex) 이전에 어떤 행동을 한 후 해당 액션을 취하니 이런 버그가 뜸
    validations:
      required: true
  - type: textarea
    attributes:
      label: 첨부파일
      description: |
        버그 내용을 사진이나 영상으로 첨부해 주세요. 용량이 큰 경우 디스코드 URL을 첨부해 주세요
      placeholder: |
        ex) 사진 혹은 [http:.....]\
    validations:
      required: true
