name: "버그 제보"
description: "버그가 생겼으면 작성해 주세요⚠️"
title: "[버그 제보]: "
body:
body:
    - type: input
    id: contact
    attributes:
      label: 연락처
      description: 디스코드 아이디를 입력해 주세요.
      placeholder: ex) 김대희#3478
    validations:
      required: false

    - type: input
    id: ios-version
    attributes:
      label: iOS 버전
      description: 사용하고 계신 기기의 iOS 버전을 입력해 주세요.
      placeholder: ex) 16.4(a)
    validations:
      required: true

    - type: input
    id: iphone-num
    attributes:
      label: iPhone 기종
      description: 사용하고 계신 iPhone 기종을 입력해 주세요.
      placeholder: ex) iPhone 14 Pro Max
    validations:
      required: true

    - type: dropdown
    id: login
    attributes:
      label: 로그인 여부
      description: 로그인은 하셨나요? 로그인하면 문제가 해결될 수도 있어요. 
      options:
        - 네, 로그인 했어요 (Default)
        - 아니요, 로그인 안했어요 (Edge)
    validations:
      required: true

    - type: dropdown
    id: login-oauth
    attributes:
      label: 로그인 방식을 선택
      description: 자신이 사용한 로그인 방식을 선택해 주세요. 
      options:
        - Google 
        - Naver
        - Apple 
    validations:
      required: false

  - type: textarea
    attributes:
      label: 버그 상세설명
      description: |
        버그를 상세히 설명해 주세요!
      placeholder: |
        ex) 이전에 어떤 행동을 한 후 해당 액션을 취하니 이런 버그가 뜸
    validations:
      required: true

  - type: textarea
    attributes:
      label: 첨부파일
      description: |
        버그 내용을 사진이나 영상으로 첨부해 주세요. 용량이 큰 경우 디스코드 URL을 첨부해 주세요
      placeholder: |
        ex) 사진 혹은 [http:.....]
    validations:
      required: true

