excluded:
    - Pods
    - WaktaverseMusicTests
    - WaktaverseMusicUITests
    
disabled_rules:
  - force_cast
  - force_try
  - type_name
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - valid_docs
  - trailing_whitespace:
        ignores_empty_lines: true
        


identifier_name:
    min_length: # min_length에서
        error: 1 # 에러만 적용
        warning: 2
    
    max_length:    # max_length에서
        warning: 40 #40글자 넘으면
        error: 50   #50글자 넘으면 에러
    excluded: # 제외할 문자열 목록 사용
        - id
        - URL
        - GlobalAPIKey

line_length:
  ignores_comments: true
