name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - "*"

env:
  CACHED_PACKAGE_DEPENDENCY_PATHS: ${{ github.workspace }}/Tuist/Dependencies
  CACHED_CARTHAGE_DEPENDENCY_PATHS: ${{ github.workspace }}/Carthage
  MASTER_KEY_PATH: Tuist/master.key
  GOOGLE_SERVICE_INFO_PLIST_PATH: Projects/App/Resources/GoogleService-Info.plist
  SECRET_XCCONFIG_PATH: Projects/App/XCConfig/Secrets.xcconfig

jobs:
  prepare-ci:
    name: ⚙️ Prepare CI
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

      - name: Compute package dependency cache key
        id: compute_package_hash
        run: echo "package_hash=${{ hashFiles('Package.swift') }}" >> $GITHUB_OUTPUT

      - name: Check package dependency cache
        uses: actions/cache@v3
        id: cache_package_dependencies
        with:
          path: ${{ env.CACHED_PACKAGE_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_package_hash.outputs.package_hash }}

      - name: Compute carthage dependency cache key
        id: compute_carthage_hash
        run: echo "carthage_hash=${{ hashFiles('Cartfile') }}" >> $GITHUB_OUTPUT

      - name: Check carthage dependency cache
        uses: actions/cache@v3
        id: cache_carthage_dependencies
        with:
          path: ${{ env.CACHED_CARTHAGE_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_carthage_hash.outputs.carthage_hash }}

      - uses: jdx/mise-action@v2
        if: steps.cache_package_dependencies.outputs.cache-hit == '' || steps.cache_carthage_dependencies.outputs.cache-hit == ''

      - name: Install tuist
        if: steps.cache_package_dependencies.outputs.cache-hit == '' || steps.cache_carthage_dependencies.outputs.cache-hit == ''
        run: |
          brew install carthage
          mise install tuist

      - name: Install dependencies needs
        if: steps.cache_package_dependencies.outputs.cache-hit == '' || steps.cache_carthage_dependencies.outputs.cache-hit == ''
        run: make install
    outputs:
      package_dependency_cache_key: ${{ steps.compute_package_hash.outputs.package_hash }}
      carthage_dependency_cache_key: ${{ steps.compute_carthage_hash.outputs.carthage_hash }}

  test:
    name: 🧪 Test
    runs-on: macos-14
    needs: prepare-ci

    steps:
      - uses: actions/checkout@v3

      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Show swift version
        run: swift --version

      - uses: jdx/mise-action@v2

      - name: Install tuist
        run: |
          brew install carthage
          mise install tuist

      - name: Check package dependency cache
        uses: actions/cache@v3
        id: cache_package_dependencies
        with:
          path: ${{ env.CACHED_PACKAGE_DEPENDENCY_PATHS }}
          key: ${{ needs.prepare-ci.outputs.package_dependency_cache_key }}

      - name: Check carthage dependency cache
        uses: actions/cache@v3
        id: cache_carthage_dependencies
        with:
          path: ${{ env.CACHED_CARTHAGE_DEPENDENCY_PATHS }}
          key: ${{ needs.prepare-ci.outputs.carthage_dependency_cache_key }}

      - name: Install dependencies needs
        if: steps.cache_package_dependencies.outputs.cache-hit != 'true' || steps.cache_carthage_dependencies.outputs.cache-hit != 'true'
        run: make install

      - name: Make `Secrets.xcconfig`
        run: |
          mkdir Projects/App/XCConfig
          touch ${{ env.SECRET_XCCONFIG_PATH }}
          echo "" > ${{ env.SECRET_XCCONFIG_PATH }}

      - name: Make `GoogleService-Info.plist`
        run: |
          touch ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }}
          echo "${{ secrets.GOOGLE_INFO_PLIST }}" > ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }}

      - name: Test with tuist
        run: make test
